### ISSUE TITLE
Ajuste dos templates HTML

### ISSUE THREAD

**Issue by nathaliaitaliano** [CaravanaCloud/thedevconf#20]
#### Hey \o/
Preciso de ajuda com alguns tópicos relacionados aos templates HTML:

> * Verificar se temos uma estrutura HTML adequada (fazer ajustes e eliminar o que não for necessário);
> * Ajustar os templates para visualização mobile, atenção especial para:
>   _Tamanho das fontes;
>   _Tamanho dos botões;
>   _ Área de badges -em userProfile.html-;
>   _Área dos benefícios dos cupons -em userCoupons.html-;

:)

**Comment by faermanj** [comment]
Te ajudo em algo aqui @nathaliaitaliano ?
