### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by faermanj** [CaravanaCloud/thedevconf#36]
Update the READE to reflect current and tested commands, best practices, IDE setup, cloud setup and other ideas.

**Comment by camilocarlos** [comment]
Pessoal, estou pensando nesses tópicos iniciais para atualizar o README do projeto:

- Introduction
- Technologies
- Running the projects locally
- IDE Setup
	- InteliJ
	- Eclipse
- License
- Contributing

@faermanj , tenho as seguintes dúvidas/tópicos que impacta na elaboração do README:
- No README tem um TODO no tópico de Start the Registration Application, será uma aplicação separada?
- Sobre a licença, temos de definir qual  será utilizada.
- Ia sugerir já adotarmos um Code Style, pois mais pessoas  contribuindo em IDEs diferente pode ter diferenças na formatação. Tem o do [Google](https://google.github.io/styleguide/javaguide.html). 
- Comentou na descrição da issue sobre cloud setup, já tem alguma configuração na AWS ou vamos fazer isso depois?

@dearrudam , @marcuxyz , @nathaliaitaliano , poderiam opinar sobre os comentários acima também ou comentar algo que deveria ter no README, por favor.

Obrigado!

**Comment by faermanj** [comment]
- "Registration Application" atualmente é o mesmo módulo, no futuro talvez seja "desmembrado" em "registration", "call for papers", and other modules/services.
- Licença MIT License
- CodeStyle do google OK!
- Setup do cloud a fazer, nao adicionar ainda
- Considerar Linux/Mac e Windows
- Testar em algumas maquinas diferentes
- Tentar simplificar
- Igualmente nos outros projetos

**Comment by faermanj** [comment]
@camilocarlos estou revisando algumas coisas para a apresentacao de hoje
