### ISSUE TITLE
Adquirir acesso ao código fonte legado

### ISSUE THREAD

**Issue by dearrudam** [CaravanaCloud/thedevconf#63]
@faermanj , por favor, forneça o acesso ao source do legado responsável pelos registros dos passaportes ao TDC

**Comment by ana-abrantes** [comment]
@dearrudam posso ter dar acesso também no ambiente onde estão os repositórios?
O Basic Pass hoje, como está vindo de formulários do RDStation, está entrando pelo sistema de inscrições via uma classe que adaptei para funcionar como endpoint e nela tem toda a lógica de incluir um novo member ou usar um existente buscando por email, e em seguida registra a inscrição propriamente dita.

**Comment by dearrudam** [comment]
@ana-abrantes seria ideal ao meu ver... saber quais são os endpoints e seus parâmetros e tal é o principal... daí a gente vai atacando os tipos de registro de maneira progressiva... se quiser, podemos falar pelo Discord ou por Google Meeting e alinhar essa parte de integração... @ericafolli , @faermanj e @camilocarlos estão convidados...

**Comment by dearrudam** [comment]
Consegui acessar os fontes. Obrigado @ana-abrantes ;
